# Generated by Django 5.2.7 on 2025-11-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='AminTAI CRM', max_length=255)),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('language', models.CharField(default='en', max_length=50)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('accent_color', models.CharField(default='#0d6efd', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CRM Settings',
                'verbose_name_plural': 'CRM Settings',
            },
        ),
    ]
